import sqlite3
conn = sqlite3.connect("saas.db")
cur = conn.cursor()
print("--- STORES ---")
for row in cur.execute("PRAGMA table_info(stores)"): print(row[1])
print("--- USERS ---")
for row in cur.execute("PRAGMA table_info(users)"): print(row[1])
print("--- PRODUCTS ---")
for row in cur.execute("PRAGMA table_info(products)"): print(row[1])
print("--- ORDERS ---")
for row in cur.execute("PRAGMA table_info(orders)"): print(row[1])
print("--- CONVERSATIONS ---")
for row in cur.execute("PRAGMA table_info(conversations)"): print(row[1])
print("--- MESSAGES ---")
for row in cur.execute("PRAGMA table_info(messages)"): print(row[1])
