import sys
import re

html_path = 'src/templates/merchant.html'

with open(html_path, 'r', encoding='utf-8') as f:
    html = f.read()

replacements = {
    # Dashboard
    "إجمالي المحادثات": "{{ _('total_chats') }}",
    "إجمالي الطلبات": "{{ _('total_orders_dashboard') }}",
    "معدل التحويل (Paid)": "{{ _('conversion_rate_paid') }}",
    "إجمالي الـ Tokens المستهلكة": "{{ _('total_tokens_used') }}",
    "استهلاك التوكنز (الذكاء الاصطناعي)": "{{ _('token_usage_chart') }}",
    "يومياً": "{{ _('daily') }}",
    "حالة النظام": "{{ _('system_health') }}",
    "متوسط سرعة الرد": "{{ _('avg_reply_speed') }}",
    "حالة اتصال Redis Live": "{{ _('redis_conn_status') }}",
    "متصل 🟢": "{{ _('connected_dot') }}",
    "عمليات AI (Interactions)": "{{ _('ai_interactions_lbl') }}",

    # CRM Tab
    "المحادثات": "{{ _('chats_lbl') }}",
    "ابحث عن عميل...": "{{ _('search_customer_placeholder') }}",
    "يحتاج تدخل 🔴": "{{ _('needs_human_btn') }}",
    "الذكاء نشط 🤖": "{{ _('ai_active_btn') }}",
    "بانتظار ردك...": "{{ _('waiting_your_reply') }}",
    "🤖 الذكاء يتحدث": "{{ _('ai_is_talking') }}",
    "لا توجد محادثات حتى الآن.": "{{ _('no_conversations_yet') }}",
    "اختر محادثة للبدء": "{{ _('choose_chat_to_start') }}",
    "يمكنك المراقبة أو استلام المحادثة آلياً": "{{ _('monitor_or_takeover') }}",
    "اسم العميل": "{{ _('customer_name_ph') }}",
    "جاري التحميل...": "{{ _('loading_ph') }}",
    "اكتب رسالة للعميل...": "{{ _('type_msg_to_customer') }}",
    "إنهاء التدخل ✅": "{{ _('end_intervention_btn') }}",

    # Products Tab
    "إدارة المخزون والتسعير": "{{ _('inventory_pricing_mgmt') }}",
    "+ إضافة منتج جديد": "{{ _('add_new_product_btn') }}",
    "الوصف الموجه للذكاء الاصطناعي": "{{ _('ai_directed_desc') }}",
    "رابط الصورة (URL)": "{{ _('image_url_lbl') }}",
    "التصنيف": "{{ _('category_lbl') }}",
    "في المخزون": "{{ _('in_inventory') }}",
    "بدون صورة": "{{ _('no_image_lbl') }}",
    "المقاسات (اضغط للتعديل)": "{{ _('sizes_click_to_edit') }}",
    "بدون مقاسات": "{{ _('no_sizes_lbl') }}",
    "نشط المبيع": "{{ _('active_sale_btn') }}",
    "متوقف": "{{ _('paused_btn') }}",
    "تأكيد الحذف؟": "{{ _('confirm_delete') }}",
    
    # Orders
    "الطلبات المنجزة بانتظار الشحن": "{{ _('completed_orders_shipping') }}",
    "العميل": "{{ _('customer_tb') }}",
    "القيمة": "{{ _('value_tb') }}",
    "الدفع معلق": "{{ _('payment_pending') }}",
    "تأكيد المالي": "{{ _('financial_confirm') }}",

    # Broadcast
    "إنشاء حملة إعلانية 📢": "{{ _('create_ad_campaign') }}",
    "سيتم إرسال هذه الرسالة إلى جميع عملائك عبر روبوت التلغرام (عدد المستهدفين:": "{{ _('broadcast_warning_start') }}",
    "عميل).": "{{ _('customers_end') }}",
    "اكتب عرضك الترويجي هنا...": "{{ _('write_promo_offer') }}",
    "إرسال الحملة فوراً 🚀": "{{ _('send_campaign_now') }}",

    # Settings
    "دور الذكاء الاصطناعي المستهدف (AI Mode)": "{{ _('ai_mode_target') }}",
    "مبيعات وإقناع (Sales)": "{{ _('sales_persuasion_mode') }}",
    "دعم فني وخدمة عملاء (Support)": "{{ _('tech_support_mode') }}",
    "مستشار موضوعي (Consultant)": "{{ _('objective_consultant_mode') }}",
    "خدمة حجوزات (Booking)": "{{ _('booking_service_mode') }}",
    "يحدد هذا الخيار كيفية تصرف الذكاء الاصطناعي مع العميل وتوجيهه نحو الدفع أو الحجز أو الإرشاد.": "{{ _('ai_mode_desc') }}",
    
    "لغة المساعد الذكي (AI Language)": "{{ _('ai_language_lbl') }}",
    "العربية (Arabic)": "{{ _('arabic_lang_opt') }}",
    "الإنجليزية (English)": "{{ _('english_lang_opt') }}",
    "التركية (Turkish)": "{{ _('turkish_lang_opt') }}",
    "سيجبر الذكاء الاصطناعي على التحدث حصراً بهذه اللغة مع عملائك.": "{{ _('ai_lang_desc') }}",
    
    "نبرة وصوت الذكاء الاصطناعي (AI Tone)": "{{ _('ai_tone_voice') }}",
    "احترافي ورسمي (Professional)": "{{ _('pro_formal_tone') }}",
    "ودود وترحاب (Friendly)": "{{ _('friendly_welcoming_tone') }}",
    "شبابي وحيوي (Youthful)": "{{ _('youthful_vibrant_tone') }}",
    "شديد الرسمية والجدية (Formal)": "{{ _('strict_formal_tone') }}",

    "سياسة المتجر أو الشروط (اختياري)": "{{ _('store_policy_opt') }}",
    "مثال: يمنع استرجاع المبالغ بعد الشحن...": "{{ _('policy_placeholder') }}",
    "سيتم إطعام هذه المعلومات ضمن سياق (Context) الذكاء الاصطناعي.": "{{ _('policy_desc') }}",
    "الإعدادات 💾": "{{ _('settings_floppy') }}",

    # Test Mode
    "معاينة تفكير الذكاء الاصطناعي (Test Mode)": "{{ _('ai_thinking_preview') }}",
    "أهلاً، كيف يمكنني الطلب؟": "{{ _('hello_how_to_order') }}",
    "اختبر الرد <span>🧠</span>": "{{ _('test_reply_btn') }}",
}

for ar, key in replacements.items():
    html = html.replace(ar, key)

html = html.replace("جرب التحدث مع مساعد متجرك لاختبار النبرة والشخصية المختارة (هذه المحادثة لا ت{{ _('save') }} ولا تؤثر على الإحصائيات).", "{{ _('try_talking_to_assistant') }}")
html = html.replace("الكل", "{{ _('all_lbl') }}")
html = html.replace("إرسال <span>➤</span>", "{{ _('send_arrow') }}")
html = html.replace("تأكيد: هل أنت متأكد من تغيير حالة التدخل البشري والذكاء الاصطناعي لهذه المحادثة؟", "{{ _('confirm_human_ai_toggle') }}")
html = html.replace("⏳ جاري معالجة الطلب في خوادم OpenAI...", "{{ _('processing_openai') }}")
html = html.replace("رد المساعد الافتراضي:", "{{ _('virtual_assistant_reply') }}")
html = html.replace("فشل الاتصال بالخادم.", "{{ _('failed_server_conn') }}")
html = html.replace(">خطأ:<", ">{{ _('error_lbl') }}<")
html = html.replace("الكل", "{{ _('all_lbl') }}")
html = html.replace("الذكاء نشط 🤖", "{{ _('ai_active_btn') }}")

with open(html_path, 'w', encoding='utf-8') as f:
    f.write(html)

i18n_path = 'src/utils/i18n.py'

with open(i18n_path, 'r', encoding='utf-8') as f:
    i18n = f.read()

new_ar = """
        "total_orders_dashboard": "إجمالي الطلبات",
        "conversion_rate_paid": "معدل التحويل (Paid)",
        "total_tokens_used": "إجمالي الـ Tokens المستهلكة",
        "token_usage_chart": "استهلاك التوكنز (الذكاء الاصطناعي)",
        "daily": "يومياً",
        "system_health": "حالة النظام",
        "avg_reply_speed": "متوسط سرعة الرد",
        "redis_conn_status": "حالة اتصال Redis Live",
        "connected_dot": "متصل 🟢",
        "ai_interactions_lbl": "عمليات AI (Interactions)",
        "chats_lbl": "المحادثات",
        "search_customer_placeholder": "ابحث عن عميل...",
        "all_lbl": "الكل",
        "needs_human_btn": "يحتاج تدخل 🔴",
        "ai_active_btn": "الذكاء نشط 🤖",
        "waiting_your_reply": "بانتظار ردك...",
        "ai_is_talking": "🤖 الذكاء يتحدث",
        "no_conversations_yet": "لا توجد محادثات حتى الآن.",
        "choose_chat_to_start": "اختر محادثة للبدء",
        "monitor_or_takeover": "يمكنك المراقبة أو استلام المحادثة آلياً",
        "customer_name_ph": "اسم العميل",
        "loading_ph": "جاري التحميل...",
        "type_msg_to_customer": "اكتب رسالة للعميل...",
        "end_intervention_btn": "إنهاء التدخل ✅",
        "inventory_pricing_mgmt": "إدارة المخزون والتسعير",
        "add_new_product_btn": "+ إضافة منتج جديد",
        "ai_directed_desc": "الوصف الموجه للذكاء الاصطناعي",
        "image_url_lbl": "رابط الصورة (URL)",
        "category_lbl": "التصنيف",
        "in_inventory": "في المخزون",
        "no_image_lbl": "بدون صورة",
        "sizes_click_to_edit": "المقاسات (اضغط للتعديل)",
        "no_sizes_lbl": "بدون مقاسات",
        "active_sale_btn": "نشط المبيع",
        "paused_btn": "متوقف",
        "confirm_delete": "تأكيد الحذف؟",
        "completed_orders_shipping": "الطلبات المنجزة بانتظار الشحن",
        "value_tb": "القيمة",
        "payment_pending": "الدفع معلق",
        "financial_confirm": "تأكيد المالي",
        "create_ad_campaign": "إنشاء حملة إعلانية 📢",
        "broadcast_warning_start": "سيتم إرسال هذه الرسالة إلى جميع عملائك عبر روبوت التلغرام (عدد المستهدفين:",
        "customers_end": "عميل).",
        "write_promo_offer": "اكتب عرضك الترويجي هنا...",
        "send_campaign_now": "إرسال الحملة فوراً 🚀",
        "ai_mode_target": "دور الذكاء الاصطناعي المستهدف (AI Mode)",
        "sales_persuasion_mode": "مبيعات وإقناع (Sales)",
        "tech_support_mode": "دعم فني وخدمة عملاء (Support)",
        "objective_consultant_mode": "مستشار موضوعي (Consultant)",
        "booking_service_mode": "خدمة حجوزات (Booking)",
        "ai_mode_desc": "يحدد هذا الخيار كيفية تصرف الذكاء الاصطناعي مع العميل وتوجيهه نحو الدفع أو الحجز أو الإرشاد.",
        "ai_language_lbl": "لغة المساعد الذكي (AI Language)",
        "arabic_lang_opt": "العربية (Arabic)",
        "english_lang_opt": "الإنجليزية (English)",
        "turkish_lang_opt": "التركية (Turkish)",
        "ai_lang_desc": "سيجبر الذكاء الاصطناعي على التحدث حصراً بهذه اللغة مع عملائك.",
        "ai_tone_voice": "نبرة وصوت الذكاء الاصطناعي (AI Tone)",
        "pro_formal_tone": "احترافي ورسمي (Professional)",
        "friendly_welcoming_tone": "ودود وترحاب (Friendly)",
        "youthful_vibrant_tone": "شبابي وحيوي (Youthful)",
        "strict_formal_tone": "شديد الرسمية والجدية (Formal)",
        "store_policy_opt": "سياسة المتجر أو الشروط (اختياري)",
        "policy_placeholder": "مثال: يمنع استرجاع المبالغ بعد الشحن...",
        "policy_desc": "سيتم إطعام هذه المعلومات ضمن سياق (Context) الذكاء الاصطناعي.",
        "settings_floppy": "الإعدادات 💾",
        "ai_thinking_preview": "معاينة تفكير الذكاء الاصطناعي (Test Mode)",
        "try_talking_to_assistant": "جرب التحدث مع مساعد متجرك لاختبار النبرة والشخصية المختارة (هذه المحادثة لا تحفظ ولا تؤثر على الإحصائيات).",
        "hello_how_to_order": "أهلاً، كيف يمكنني الطلب؟",
        "test_reply_btn": "اختبر الرد <span>🧠</span>",
        "confirm_human_ai_toggle": "تأكيد: هل أنت متأكد من تغيير حالة التدخل البشري والذكاء الاصطناعي لهذه المحادثة؟",
        "processing_openai": "⏳ جاري معالجة الطلب في خوادم OpenAI...",
        "virtual_assistant_reply": "رد المساعد الافتراضي:",
        "failed_server_conn": "فشل الاتصال بالخادم.",
        "error_lbl": "خطأ:",
        "send_arrow": "إرسال <span>➤</span>",
"""

new_en = """
        "total_orders_dashboard": "Total Orders",
        "conversion_rate_paid": "Conversion Rate (Paid)",
        "total_tokens_used": "Total Tokens Consumed",
        "token_usage_chart": "Token Usage (AI)",
        "daily": "Daily",
        "system_health": "System Health",
        "avg_reply_speed": "Avg Reply Latency",
        "redis_conn_status": "Redis Live Status",
        "connected_dot": "Connected 🟢",
        "ai_interactions_lbl": "AI Interactions",
        "chats_lbl": "Conversations",
        "search_customer_placeholder": "Search customer...",
        "all_lbl": "All",
        "needs_human_btn": "Needs Human 🔴",
        "ai_active_btn": "AI Active 🤖",
        "waiting_your_reply": "Waiting your reply...",
        "ai_is_talking": "🤖 AI is talking",
        "no_conversations_yet": "No conversations yet.",
        "choose_chat_to_start": "Select a chat to start",
        "monitor_or_takeover": "You can monitor or takeover the chat",
        "customer_name_ph": "Customer Name",
        "loading_ph": "Loading...",
        "type_msg_to_customer": "Type message to customer...",
        "end_intervention_btn": "End Intervention ✅",
        "inventory_pricing_mgmt": "Inventory & Pricing Mgmt",
        "add_new_product_btn": "+ Add New Product",
        "ai_directed_desc": "AI Directed Description",
        "image_url_lbl": "Image URL",
        "category_lbl": "Category",
        "in_inventory": "in Inventory",
        "no_image_lbl": "No Image",
        "sizes_click_to_edit": "Sizes (Click to Edit)",
        "no_sizes_lbl": "No Sizes",
        "active_sale_btn": "Active Sale",
        "paused_btn": "Paused",
        "confirm_delete": "Confirm Delete?",
        "completed_orders_shipping": "Completed Orders (Awaiting Shipping)",
        "value_tb": "Value",
        "payment_pending": "Payment Pending",
        "financial_confirm": "Confirm Payment",
        "create_ad_campaign": "Create Ad Campaign 📢",
        "broadcast_warning_start": "This message will be sent to all customers via Telegram bot (Target count:",
        "customers_end": "customers).",
        "write_promo_offer": "Write your promotional offer here...",
        "send_campaign_now": "Send Campaign Now 🚀",
        "ai_mode_target": "Target AI Mode",
        "sales_persuasion_mode": "Sales & Persuasion",
        "tech_support_mode": "Tech Support & CS",
        "objective_consultant_mode": "Objective Consultant",
        "booking_service_mode": "Booking Service",
        "ai_mode_desc": "This determines how the AI acts and directs customers.",
        "ai_language_lbl": "AI Language",
        "arabic_lang_opt": "Arabic",
        "english_lang_opt": "English",
        "turkish_lang_opt": "Turkish",
        "ai_lang_desc": "Forces the AI to speak exclusively in this language.",
        "ai_tone_voice": "AI Tone & Voice",
        "pro_formal_tone": "Professional & Formal",
        "friendly_welcoming_tone": "Friendly & Welcoming",
        "youthful_vibrant_tone": "Youthful & Vibrant",
        "strict_formal_tone": "Strictly Formal",
        "store_policy_opt": "Store Policy / Ts&Cs (Optional)",
        "policy_placeholder": "Example: No refunds after shipping...",
        "policy_desc": "This context will feed the AI's knowledge base.",
        "settings_floppy": "Settings 💾",
        "ai_thinking_preview": "AI Thinking Preview (Test Mode)",
        "try_talking_to_assistant": "Try chatting with your assistant to test tone (Chats not saved).",
        "hello_how_to_order": "Hello, how can I order?",
        "test_reply_btn": "Test Reply <span>🧠</span>",
        "confirm_human_ai_toggle": "Confirm: Are you sure you want to toggle human intervention state?",
        "processing_openai": "⏳ Processing request on OpenAI servers...",
        "virtual_assistant_reply": "Virtual Assistant Reply:",
        "failed_server_conn": "Failed to connect to server.",
        "error_lbl": "Error:",
        "send_arrow": "Send <span>➤</span>",
"""

new_tr = """
        "total_orders_dashboard": "Toplam Siparişler",
        "conversion_rate_paid": "Dönüşüm Oranı (Ücretli)",
        "total_tokens_used": "Tüketilen Toplam Token",
        "token_usage_chart": "Token Kullanımı (YZ)",
        "daily": "Günlük",
        "system_health": "Sistem Sağlığı",
        "avg_reply_speed": "Ort. Yanıt Süresi",
        "redis_conn_status": "Redis Canlı Durum",
        "connected_dot": "Bağlı 🟢",
        "ai_interactions_lbl": "YZ Etkileşimleri",
        "chats_lbl": "Sohbetler",
        "search_customer_placeholder": "Müşteri ara...",
        "all_lbl": "Tümü",
        "needs_human_btn": "İnsan Gerekiyor 🔴",
        "ai_active_btn": "YZ Aktif 🤖",
        "waiting_your_reply": "Yanıtınız bekleniyor...",
        "ai_is_talking": "🤖 YZ konuşuyor",
        "no_conversations_yet": "Henüz sohbet yok.",
        "choose_chat_to_start": "Başlamak için bir sohbet seç",
        "monitor_or_takeover": "Sohbeti izleyebilir veya devralabilirsiniz",
        "customer_name_ph": "Müşteri Adı",
        "loading_ph": "Yükleniyor...",
        "type_msg_to_customer": "Müşteriye mesaj yazın...",
        "end_intervention_btn": "Müdahaleyi Bitir ✅",
        "inventory_pricing_mgmt": "Envanter ve Fiyat Yönetimi",
        "add_new_product_btn": "+ Yeni Ürün Ekle",
        "ai_directed_desc": "YZ Yönlendirmeli Açıklama",
        "image_url_lbl": "Resim URL'si",
        "category_lbl": "Kategori",
        "in_inventory": "Envanterde",
        "no_image_lbl": "Resim Yok",
        "sizes_click_to_edit": "Bedenler (Düzenlemek İçin Tıkla)",
        "no_sizes_lbl": "Beden Yok",
        "active_sale_btn": "Aktif Satış",
        "paused_btn": "Duraklatıldı",
        "confirm_delete": "Silmeyi Onayla?",
        "completed_orders_shipping": "Tamamlanan Siparişler (Sevkiyat Bekliyor)",
        "value_tb": "Değer",
        "payment_pending": "Ödeme Bekleniyor",
        "financial_confirm": "Ödemeyi Onayla",
        "create_ad_campaign": "Reklam Kampanyası Oluştur 📢",
        "broadcast_warning_start": "Bu mesaj tüm müşterilerinize Telegram botu aracılığıyla gönderilecek (Hedef sayısı:",
        "customers_end": "müşteri).",
        "write_promo_offer": "Promosyon teklifinizi buraya yazın...",
        "send_campaign_now": "Kampanyayı Şimdi Gönder 🚀",
        "ai_mode_target": "Hedef YZ Modu",
        "sales_persuasion_mode": "Satış ve İkna",
        "tech_support_mode": "Teknik Destek ve Müşteri Hizmetleri",
        "objective_consultant_mode": "Objektif Danışman",
        "booking_service_mode": "Rezervasyon Hizmeti",
        "ai_mode_desc": "Bu, YZ'nin müşterilere nasıl davranacağını ve onları nasıl yönlendireceğini belirler.",
        "ai_language_lbl": "YZ Dili",
        "arabic_lang_opt": "Arapça",
        "english_lang_opt": "İngilizce",
        "turkish_lang_opt": "Türkçe",
        "ai_lang_desc": "YZ'yi sadece bu dili konuşmaya zorlar.",
        "ai_tone_voice": "YZ Tonu ve Sesi",
        "pro_formal_tone": "Profesyonel ve Resmi",
        "friendly_welcoming_tone": "Dostça ve Misafirperver",
        "youthful_vibrant_tone": "Genç ve Canlı",
        "strict_formal_tone": "Sıkı Resmi",
        "store_policy_opt": "Mağaza Politikası / Şartlar (İsteğe Bağlı)",
        "policy_placeholder": "Örnek: Kargolamadan sonra iade yapılmaz...",
        "policy_desc": "Bu bağlam YZ'nin bilgi tabanını besleyecektir.",
        "settings_floppy": "Ayarlar 💾",
        "ai_thinking_preview": "YZ Düşünme Ön Analizi (Test Modu)",
        "try_talking_to_assistant": "Tonu test etmek için asistanınızla sohbet etmeyi deneyin (Sohbetler kaydedilmez).",
        "hello_how_to_order": "Merhaba, nasıl sipariş verebilirim?",
        "test_reply_btn": "Yanıtı Test Et <span>🧠</span>",
        "confirm_human_ai_toggle": "Onaylayın: İnsan müdahalesi durumunu değiştirmek istediğinizden emin misiniz?",
        "processing_openai": "⏳ İstek OpenAI sunucularında işleniyor...",
        "virtual_assistant_reply": "Sanal Asistan Yanıtı:",
        "failed_server_conn": "Sunucuya bağlanılamadı.",
        "error_lbl": "Hata:",
        "send_arrow": "Gönder <span>➤</span>",
"""

new_i18n = i18n
new_i18n = new_i18n.replace('"back_to_dashboard": "العودة للوحة المتجر"', '"back_to_dashboard": "العودة للوحة المتجر",\n' + new_ar)
new_i18n = new_i18n.replace('"user_anonymous": "User"', '"user_anonymous": "User",\n' + new_en)
new_i18n = new_i18n.replace('"user_anonymous": "Kullanıcı"', '"user_anonymous": "Kullanıcı",\n' + new_tr)

with open(i18n_path, 'w', encoding='utf-8') as f:
    f.write(new_i18n)

print("Patch applied successfully.")
