"""initial schema

Revision ID: d14e2911ff8e
Revises: 
Create Date: 2026-03-31 14:31:57.617402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14e2911ff8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.add_column('products', sa.Column('type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_service', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('booking_link', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('ai_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('plan', sa.String(), nullable=True))
    op.add_column('users', sa.Column('messages_used', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('messages_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'messages_limit')
    op.drop_column('users', 'messages_used')
    op.drop_column('users', 'plan')
    op.drop_column('stores', 'ai_enabled')
    op.drop_column('products', 'booking_link')
    op.drop_column('products', 'is_service')
    op.drop_column('products', 'duration')
    op.drop_column('products', 'type')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
