"""Add onboarding step column

Revision ID: ecbb389afad8
Revises: 60509408d307
Create Date: 2026-04-01 19:16:44.140662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecbb389afad8'
down_revision: Union[str, Sequence[str], None] = '60509408d307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('onboarding_step', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'onboarding_step')
    # ### end Alembic commands ###
