"""Add Plan model and billing fields

Revision ID: fb7ee05e0566
Revises: d14e2911ff8e
Create Date: 2026-04-01 18:08:28.334915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7ee05e0566'
down_revision: Union[str, Sequence[str], None] = 'd14e2911ff8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('price_usd', sa.Float(), nullable=True),
        sa.Column('monthly_token_limit', sa.Integer(), nullable=True),
        sa.Column('features', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.add_column('stores', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('subscription_status', sa.String(), nullable=True))
    
    op.create_foreign_key('fk_stores_plan_id_plans', 'stores', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_stores_plan_id_plans', 'stores', type_='foreignkey')
    op.drop_column('stores', 'subscription_status')
    op.drop_column('stores', 'plan_id')
    op.drop_table('plans')
    # ### end Alembic commands ###
